{% set name = "pyleco" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymeasure/pyleco/archive/refs/tags/v{{ version }}-cf.tar.gz
  sha256: 8b156d7ce71d80deeec39192aa2671721e301dfd86dbbf1fcb46454f66aec98c

build:
  noarch: python
  entry_points:
    - coordinator = pyleco.coordinators.coordinator:main
    - proxy_server = pyleco.coordinators.proxy_server:main
    - starter = pyleco.management.starter:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - pyzmq >=22.3.0
    - uuid6 >=2024.1.12

test:
  imports:
    - pyleco
  commands:
    - coordinator --help
    - proxy_server --help
    - starter --help
  requires:
    - pip

about:
  home: https://github.com/pymeasure/pyleco
  summary: Python reference implementation of the Laboratory Experiment COntrol (LECO) protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenediktBurger
